apiVersion: v2
name: habagou
description: Learn to write Chinese characters by tracing them, stroke by stroke.
type: application
version: 0.1.0
appVersion: "0.1.0"
kubeVersion: ">=1.27.0-0"
home: https://github.com/mattjmcnaughton/habagou
sources:
  - https://github.com/mattjmcnaughton/habagou
maintainers:
  - name: mattjmcnaughton
    url: https://github.com/mattjmcnaughton
