/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/feature-flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Feature Flags */
        get: operations["list_feature_flags_api_v1_admin_feature_flags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/feature-flags/{flag_key}/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Feature Flag Override */
        put: operations["set_feature_flag_override_api_v1_admin_feature_flags__flag_key__users__user_id__put"];
        post?: never;
        /** Clear Feature Flag Override */
        delete: operations["clear_feature_flag_override_api_v1_admin_feature_flags__flag_key__users__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Auth Session */
        get: operations["get_auth_session_api_v1_auth_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/characters/{hanzi}/strokes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Character Strokes */
        get: operations["get_character_strokes_api_v1_characters__hanzi__strokes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generation/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Draft
         * @description Draft (or refine) a corpus-grounded pack for the caller's topic.
         */
        post: operations["generate_draft_api_v1_generation_draft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generation/packs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Pack
         * @description Persist a finalized draft as a pack owned by the caller.
         */
        post: operations["save_pack_api_v1_generation_packs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generation/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Generation Status
         * @description Report whether pack generation is available, for entry-point gating.
         *
         *     The frontend calls this to decide whether to show the "Create a pack" entry
         *     point (issue #102): the button stays hidden when generation is unconfigured,
         *     so a user is never routed into a flow the ``/draft`` endpoint can only 503.
         *
         *     Deliberately cheap: no DB access beyond the auth lookup, no rate limiting,
         *     and no workflow event — it is a stateless readiness probe over a config
         *     flag, not a step in any tracked workflow (WF-15 covers the draft/save
         *     actions). Auth matches the other pack read endpoints (e.g.
         *     ``GET /api/v1/packs``); the flag is server-wide, not per-user.
         *
         *     For admin callers (and only when generation is configured) the response
         *     also carries the selectable models and the server default, which is what
         *     renders the model picker — ``models`` stays ``None`` for everyone else.
         */
        get: operations["get_generation_status_api_v1_generation_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Library */
        get: operations["get_library_api_v1_library_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/packs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Packs */
        get: operations["list_packs_api_v1_packs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/packs/{pack_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pack */
        get: operations["get_pack_api_v1_packs__pack_id__get"];
        put?: never;
        post?: never;
        /** Delete Pack */
        delete: operations["delete_pack_api_v1_packs__pack_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/packs/{pack_id}/enabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Pack Enabled */
        put: operations["set_pack_enabled_api_v1_packs__pack_id__enabled_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/path": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Path */
        get: operations["get_path_api_v1_path_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/path/items/{item_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Path Item */
        post: operations["complete_path_item_api_v1_path_items__item_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/practice/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Practice Status
         * @description Report whether conversational practice is available, for UI gating.
         *
         *     The Practice tab always renders; the practice screen calls this to decide
         *     between the topic picker and an unavailable state, so a user is never
         *     routed into a flow the ``/turn`` endpoint can only 503. Deliberately
         *     cheap, mirroring ``GET /api/v1/generation/status``: a stateless readiness
         *     probe over a config flag — no rate limiting, no workflow event.
         *
         *     For admin callers (and only when practice is configured) the response also
         *     carries the selectable models and the server default, which is what
         *     renders the model picker — ``models`` stays ``None`` for everyone else.
         */
        get: operations["get_practice_status_api_v1_practice_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/practice/turn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Practice Turn
         * @description Run one tutor turn for the caller's message (or opening topic).
         */
        post: operations["practice_turn_api_v1_practice_turn_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/progress/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Completion */
        post: operations["create_completion_api_v1_progress_completions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/progress/packs/{pack_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pack Progress */
        get: operations["get_pack_progress_api_v1_progress_packs__pack_id__get"];
        put?: never;
        post?: never;
        /** Reset Pack Progress */
        delete: operations["reset_pack_progress_api_v1_progress_packs__pack_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/progress/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Progress Summary */
        get: operations["get_progress_summary_api_v1_progress_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Auth Callback */
        get: operations["auth_callback_auth_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Login */
        get: operations["login_auth_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness probe.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Readiness probe.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityProgressDTO */
        ActivityProgressDTO: {
            /** Best Duration Ms */
            best_duration_ms: number | null;
            /** Completed */
            completed: boolean;
            /** Completion Count */
            completion_count: number;
        };
        /**
         * ActivityType
         * @description Activity variants that can create completion events.
         * @enum {string}
         */
        ActivityType: "trace" | "match" | "sentence";
        /**
         * ChatModelOptionDTO
         * @description One selectable model: the OpenRouter id plus a display label.
         */
        ChatModelOptionDTO: {
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /** CompletionCreateDTO */
        CompletionCreateDTO: {
            activity: components["schemas"]["ActivityType"];
            /** Duration Ms */
            duration_ms: number;
            /**
             * Pack Id
             * Format: uuid
             */
            pack_id: string;
        };
        /** CompletionResponseDTO */
        CompletionResponseDTO: {
            activity: components["schemas"]["ActivityType"];
            /** Duration Ms */
            duration_ms: number;
            progress: components["schemas"]["PackProgressDTO"];
        };
        /** DailyActivityDTO */
        DailyActivityDTO: {
            /** Count */
            count: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Level */
            level: number;
        };
        /** DailyGoalDTO */
        DailyGoalDTO: {
            /** Completed */
            completed: number;
            /** Target */
            target: number;
        };
        /**
         * FeatureFlagDTO
         * @description One code-defined flag: its effective default and per-user override count.
         */
        FeatureFlagDTO: {
            /** Enabled Default */
            enabled_default: boolean;
            /** Key */
            key: string;
            /** Override Count */
            override_count: number;
        };
        /** FeatureFlagListDTO */
        FeatureFlagListDTO: {
            /** Flags */
            flags: components["schemas"]["FeatureFlagDTO"][];
        };
        /** FeatureFlagOverrideDTO */
        FeatureFlagOverrideDTO: {
            /** Enabled */
            enabled: boolean;
            /** Flag Key */
            flag_key: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** FeatureFlagOverrideSetDTO */
        FeatureFlagOverrideSetDTO: {
            /** Enabled */
            enabled: boolean;
        };
        /**
         * GenerationDraftRequestDTO
         * @description Request to draft (or refine) a pack from a topic.
         *
         *     ``history`` is the opaque JSON message history returned by a prior draft
         *     turn (see :class:`GenerationDraftResponseDTO`); replaying it lets a
         *     refinement turn keep the model's context. It is ``None`` on the first turn.
         */
        GenerationDraftRequestDTO: {
            /** History */
            history?: unknown[] | null;
            /** Model */
            model?: string | null;
            /** Topic */
            topic: string;
        };
        /**
         * GenerationDraftResponseDTO
         * @description A drafted pack plus the updated conversation history to persist.
         *
         *     The client holds ``history`` between turns and passes it back on the next
         *     :class:`GenerationDraftRequestDTO` to refine the draft.
         */
        GenerationDraftResponseDTO: {
            draft: components["schemas"]["PackDraft"];
            /** History */
            history: unknown[];
        };
        /**
         * GenerationSavePackRequestDTO
         * @description Request to persist a finalized :class:`PackDraft` as an owned pack.
         */
        GenerationSavePackRequestDTO: {
            draft: components["schemas"]["PackDraft"];
        };
        /**
         * GenerationStatusDTO
         * @description Whether agent pack generation is available, for entry-point gating.
         *
         *     The frontend calls this before deciding whether to surface the "Create a
         *     pack" entry point (issue #102 / mockup): when generation is unconfigured the
         *     button stays hidden, so a user is never offered a flow that can only 503.
         *     ``enabled`` mirrors :attr:`habagou.config.Settings.generation_configured`
         *     (True only when both the OpenRouter key and the model are set); it is not a
         *     per-user capability, just a server-wide readiness flag.
         *
         *     ``models`` and ``default_model`` are the admin model picker's data: the
         *     selectable OpenRouter models (default first) and the id that runs when the
         *     request carries no override. Both are ``None`` for non-admin callers — the
         *     response itself gates the picker UI — and when generation is unconfigured.
         */
        GenerationStatusDTO: {
            /** Default Model */
            default_model?: string | null;
            /** Enabled */
            enabled: boolean;
            /** Models */
            models?: components["schemas"]["ChatModelOptionDTO"][] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LibraryCategoryDTO */
        LibraryCategoryDTO: {
            /** Packs */
            packs: components["schemas"]["LibraryPackDTO"][];
            /** Slug */
            slug: string;
            /** Title */
            title: string;
        };
        /** LibraryDTO */
        LibraryDTO: {
            /** Categories */
            categories: components["schemas"]["LibraryCategoryDTO"][];
        };
        /**
         * LibraryPackDTO
         * @description Slim library card: no progress aggregates (the library lists hundreds
         *     of packs; per-pack progress stays a bench concern).
         */
        LibraryPackDTO: {
            /** Char Count */
            char_count: number;
            /** Color */
            color: string;
            /** Description */
            description: string | null;
            /** Enabled */
            enabled: boolean;
            /** Glyph */
            glyph: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Sentence Count */
            sentence_count: number;
            /** Starter */
            starter: boolean;
            /** Title */
            title: string;
        };
        /** NextMilestoneDTO */
        NextMilestoneDTO: {
            /** Days Remaining */
            days_remaining: number;
            /** Progress Pct */
            progress_pct: number;
            /** Target Days */
            target_days: number;
        };
        /** PackCharacterDTO */
        PackCharacterDTO: {
            /** Hanzi */
            hanzi: string;
            /** Meaning */
            meaning: string;
            /** Pinyin */
            pinyin: string;
        };
        /** PackDetailDTO */
        PackDetailDTO: {
            /** Char Count */
            char_count: number;
            /** Characters */
            characters: components["schemas"]["PackCharacterDTO"][];
            /** Color */
            color: string;
            /** Enabled */
            enabled: boolean;
            /** Glyph */
            glyph: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Owned */
            owned: boolean;
            progress: components["schemas"]["PackProgressDTO"];
            /** Sentence Count */
            sentence_count: number;
            /** Sentences */
            sentences: components["schemas"]["PackSentenceDTO"][];
            /** Starter */
            starter: boolean;
            /** Title */
            title: string;
        };
        /**
         * PackDraft
         * @description Structured output the generation agent returns for a practice pack.
         */
        PackDraft: {
            /** Characters */
            characters: components["schemas"]["PackDraftCharacter"][];
            /** Coverage Note */
            coverage_note?: string | null;
            /** Sentences */
            sentences?: components["schemas"]["PackDraftSentence"][];
            /** Title */
            title: string;
        };
        /**
         * PackDraftCharacter
         * @description A single drafted character with its model-generated gloss.
         */
        PackDraftCharacter: {
            /** Hanzi */
            hanzi: string;
            /** Meaning */
            meaning: string;
            /** Pinyin */
            pinyin: string;
        };
        /**
         * PackDraftSentence
         * @description A drafted example sentence for the sentence-tracing activity.
         */
        PackDraftSentence: {
            /** Hanzi */
            hanzi: string;
            /** Pinyin */
            pinyin: string;
            /** Translation */
            translation: string;
        };
        /** PackEnablementUpdateDTO */
        PackEnablementUpdateDTO: {
            /** Enabled */
            enabled: boolean;
        };
        /** PackProgressDTO */
        PackProgressDTO: {
            match: components["schemas"]["ActivityProgressDTO"];
            sentence: components["schemas"]["ActivityProgressDTO"];
            trace: components["schemas"]["ActivityProgressDTO"];
        };
        /** PackProgressResponseDTO */
        PackProgressResponseDTO: {
            progress: components["schemas"]["PackProgressDTO"];
        };
        /** PackSentenceDTO */
        PackSentenceDTO: {
            /** Hanzi */
            hanzi: string;
            /** Pinyin */
            pinyin: string;
            /** Translation */
            translation: string;
        };
        /** PackSummaryDTO */
        PackSummaryDTO: {
            /** Char Count */
            char_count: number;
            /** Color */
            color: string;
            /** Enabled */
            enabled: boolean;
            /** Glyph */
            glyph: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Owned */
            owned: boolean;
            progress: components["schemas"]["PackProgressDTO"];
            /** Sentence Count */
            sentence_count: number;
            /** Starter */
            starter: boolean;
            /** Title */
            title: string;
        };
        /** PathCharDTO */
        PathCharDTO: {
            /** Hanzi */
            hanzi: string;
            /** Meaning */
            meaning: string;
            /** Pinyin */
            pinyin: string;
        };
        PathContentDTO: {
            [key: string]: unknown;
        };
        /** PathDailyDTO */
        PathDailyDTO: {
            /** Completed */
            completed: number;
            /** Target */
            target: number;
        };
        /** PathDueDTO */
        PathDueDTO: {
            /** New */
            new: number;
            /** Review */
            review: number;
        };
        /** PathItemCompleteDTO */
        PathItemCompleteDTO: {
            /** Duration Ms */
            duration_ms: number;
        };
        /** PathItemCompleteResponseDTO */
        PathItemCompleteResponseDTO: {
            daily: components["schemas"]["PathDailyDTO"];
            /**
             * Item Id
             * Format: uuid
             */
            item_id: string;
            /** Next Item Id */
            next_item_id: string | null;
            /** Streak */
            streak: number;
        };
        /** PathItemDTO */
        PathItemDTO: {
            /**
             * Activity
             * @enum {string}
             */
            activity: "trace" | "match" | "sentence";
            content: components["schemas"]["PathContentDTO"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "new" | "review";
            pack: components["schemas"]["PathPackDTO"];
            /** Position */
            position: number;
            /**
             * State
             * @enum {string}
             */
            state: "done" | "current" | "locked";
            /** Unit Label */
            unit_label: string | null;
        };
        /** PathMatchContentDTO */
        PathMatchContentDTO: {
            /** Pairs */
            pairs: components["schemas"]["PathCharDTO"][];
        };
        /** PathPackDTO */
        PathPackDTO: {
            /** Color */
            color: string;
            /** Glyph */
            glyph: string;
            /** Title */
            title: string;
        };
        /** PathResponseDTO */
        PathResponseDTO: {
            daily: components["schemas"]["PathDailyDTO"];
            due: components["schemas"]["PathDueDTO"];
            /** Items */
            items: components["schemas"]["PathItemDTO"][];
            /** Next Cursor */
            next_cursor: number | null;
            /** Streak */
            streak: number;
        };
        /** PathSentenceContentDTO */
        PathSentenceContentDTO: {
            /** Hanzi */
            hanzi: string;
            /** Pinyin */
            pinyin: string;
            /** Translation */
            translation: string;
        };
        /** PathTraceContentDTO */
        PathTraceContentDTO: {
            /** Chars */
            chars: components["schemas"]["PathCharDTO"][];
        };
        /**
         * PracticeSegment
         * @description One sentence of a tutor reply, carried three ways.
         *
         *     ``english`` is generated with every segment even though the UI hides it
         *     behind a tap — a few dozen output tokens buys instant reveal with no second
         *     model call.
         */
        PracticeSegment: {
            /** English */
            english: string;
            /** Hanzi */
            hanzi: string;
            /** Pinyin */
            pinyin: string;
        };
        /**
         * PracticeStatusDTO
         * @description Whether conversational practice is available, for entry-point gating.
         *
         *     ``enabled`` mirrors :attr:`habagou.config.Settings.practice_configured`.
         *     The Practice tab renders regardless (hiding a tab on an async fetch would
         *     shift the app shell); the practice screen itself shows an unavailable
         *     state when this reports ``False``, so a user is never routed into a flow
         *     the ``/turn`` endpoint can only 503.
         *
         *     ``models`` and ``default_model`` are the admin model picker's data,
         *     mirroring :class:`habagou.dtos.generation.GenerationStatusDTO`: ``None``
         *     for non-admin callers (the response gates the picker UI) and when practice
         *     is unconfigured.
         */
        PracticeStatusDTO: {
            /** Default Model */
            default_model?: string | null;
            /** Enabled */
            enabled: boolean;
            /** Models */
            models?: components["schemas"]["ChatModelOptionDTO"][] | null;
        };
        /**
         * PracticeTurn
         * @description Structured output the practice agent returns for one tutor reply.
         *
         *     ``english_aside`` is the "break glass" channel: filled only when the
         *     learner asked for help in English, and rendered as a distinct helper
         *     bubble while ``segments`` continue the conversation in Chinese.
         */
        PracticeTurn: {
            /** English Aside */
            english_aside?: string | null;
            /** Segments */
            segments: components["schemas"]["PracticeSegment"][];
        };
        /**
         * PracticeTurnRequestDTO
         * @description Request for one practice turn.
         *
         *     On the first turn of a conversation ``message`` is the learner's chosen
         *     topic (the system prompt tells the tutor to open the conversation from
         *     it) and ``history`` is ``None``. On later turns ``message`` is the
         *     learner's chat input — English, Chinese, or mixed — and ``history`` is the
         *     opaque JSON message history a prior turn returned (see
         *     :class:`PracticeTurnResponseDTO`); replaying it keeps the model's context
         *     with no server-side conversation store.
         */
        PracticeTurnRequestDTO: {
            /** History */
            history?: unknown[] | null;
            /** Message */
            message: string;
            /** Model */
            model?: string | null;
        };
        /**
         * PracticeTurnResponseDTO
         * @description A tutor reply plus the updated conversation history to hold client-side.
         *
         *     The client keeps ``history`` between turns and passes it back on the next
         *     :class:`PracticeTurnRequestDTO`. Conversations are ephemeral by design:
         *     discarding the history is how a conversation ends.
         */
        PracticeTurnResponseDTO: {
            /** History */
            history: unknown[];
            turn: components["schemas"]["PracticeTurn"];
        };
        /** ProgressResetDTO */
        ProgressResetDTO: {
            /** Deleted Count */
            deleted_count: number;
            progress: components["schemas"]["PackProgressDTO"];
        };
        /** ProgressSummaryDTO */
        ProgressSummaryDTO: {
            /** Activity */
            activity: components["schemas"]["DailyActivityDTO"][];
            /** Best Streak */
            best_streak: number;
            /** Characters Traced */
            characters_traced: number;
            /** Current Streak */
            current_streak: number;
            daily_goal: components["schemas"]["DailyGoalDTO"];
            next_milestone: components["schemas"]["NextMilestoneDTO"];
            /** Packs Completed */
            packs_completed: number;
            /** Packs Total */
            packs_total: number;
        };
        /** SessionDTO */
        SessionDTO: {
            /** Authenticated */
            authenticated: boolean;
            /** Provider */
            provider: string;
            user?: components["schemas"]["UserDTO"] | null;
        };
        /** UserDTO */
        UserDTO: {
            /** Display Name */
            display_name: string;
            /** Email */
            email?: string | null;
            /**
             * Feature Flags
             * @default {}
             */
            feature_flags: {
                [key: string]: boolean;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Is Admin
             * @default false
             */
            is_admin: boolean;
            /** Username */
            username: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_feature_flags_api_v1_admin_feature_flags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureFlagListDTO"];
                };
            };
        };
    };
    set_feature_flag_override_api_v1_admin_feature_flags__flag_key__users__user_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                flag_key: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeatureFlagOverrideSetDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureFlagOverrideDTO"];
                };
            };
            /** @description Unknown flag or user */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_feature_flag_override_api_v1_admin_feature_flags__flag_key__users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                flag_key: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown flag */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_auth_session_api_v1_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDTO"];
                };
            };
        };
    };
    get_character_strokes_api_v1_characters__hanzi__strokes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hanzi: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Hanzi Writer stroke JSON */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Character stroke data not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Path parameter must be exactly one grapheme */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    generate_draft_api_v1_generation_draft_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerationDraftRequestDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationDraftResponseDTO"];
                };
            };
            /** @description Model selection requires an admin account */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Replayed history is invalid, or the requested model is not selectable */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Per-user generation rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Pack generation failed */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Pack generation is not configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    save_pack_api_v1_generation_packs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerationSavePackRequestDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackDetailDTO"];
                };
            };
            /** @description Draft references non-corpus characters */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_generation_status_api_v1_generation_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationStatusDTO"];
                };
            };
        };
    };
    get_library_api_v1_library_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryDTO"];
                };
            };
        };
    };
    list_packs_api_v1_packs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackSummaryDTO"][];
                };
            };
        };
    };
    get_pack_api_v1_packs__pack_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pack_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackDetailDTO"];
                };
            };
            /** @description Pack not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_pack_api_v1_packs__pack_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pack_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Cannot delete a curated pack */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Pack not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_pack_enabled_api_v1_packs__pack_id__enabled_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pack_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PackEnablementUpdateDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Pack not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Owned packs are always enabled */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_path_api_v1_path_get: {
        parameters: {
            query?: {
                cursor?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PathResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_path_item_api_v1_path_items__item_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PathItemCompleteDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PathItemCompleteResponseDTO"];
                };
            };
            /** @description Path item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Path item already completed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_practice_status_api_v1_practice_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeStatusDTO"];
                };
            };
        };
    };
    practice_turn_api_v1_practice_turn_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PracticeTurnRequestDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeTurnResponseDTO"];
                };
            };
            /** @description Model selection requires an admin account */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Replayed history is invalid, or the requested model is not selectable */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Per-user practice rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Practice turn failed */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conversational practice is not configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_completion_api_v1_progress_completions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompletionCreateDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletionResponseDTO"];
                };
            };
            /** @description Pack not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pack_progress_api_v1_progress_packs__pack_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pack_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackProgressResponseDTO"];
                };
            };
            /** @description Pack not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_pack_progress_api_v1_progress_packs__pack_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pack_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressResetDTO"];
                };
            };
            /** @description Pack not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_progress_summary_api_v1_progress_summary_get: {
        parameters: {
            query?: {
                tz_offset_minutes?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressSummaryDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_callback_auth_callback_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    login_auth_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
