/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/packs/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Pack */
        patch: operations["patch_pack_api_v1_admin_packs__slug__patch"];
        trace?: never;
    };
    "/api/v1/admin/packs/{slug}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Pack */
        post: operations["publish_pack_api_v1_admin_packs__slug__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/packs/{slug}/retire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retire Pack */
        post: operations["retire_pack_api_v1_admin_packs__slug__retire_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/characters/{hanzi}/strokes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Character Strokes */
        get: operations["get_character_strokes_api_v1_characters__hanzi__strokes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/packs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Packs */
        get: operations["list_packs_api_v1_packs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/packs/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pack */
        get: operations["get_pack_api_v1_packs__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/progress/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Completion */
        post: operations["create_completion_api_v1_progress_completions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/progress/packs/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pack Progress */
        get: operations["get_pack_progress_api_v1_progress_packs__slug__get"];
        put?: never;
        post?: never;
        /** Reset Pack Progress */
        delete: operations["reset_pack_progress_api_v1_progress_packs__slug__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/progress/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Progress Summary */
        get: operations["get_progress_summary_api_v1_progress_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness probe.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Readiness probe.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityProgressDTO */
        ActivityProgressDTO: {
            /** Best Duration Ms */
            best_duration_ms: number | null;
            /** Completed */
            completed: boolean;
            /** Completion Count */
            completion_count: number;
        };
        /**
         * ActivityType
         * @description Activity variants that can create completion events.
         * @enum {string}
         */
        ActivityType: "trace" | "match" | "sentence";
        /** CompletionCreateDTO */
        CompletionCreateDTO: {
            activity: components["schemas"]["ActivityType"];
            /** Duration Ms */
            duration_ms: number;
            /** Pack Slug */
            pack_slug: string;
        };
        /** CompletionResponseDTO */
        CompletionResponseDTO: {
            activity: components["schemas"]["ActivityType"];
            /** Duration Ms */
            duration_ms: number;
            /** Pack Slug */
            pack_slug: string;
            progress: components["schemas"]["PackProgressDTO"];
        };
        /** DailyActivityDTO */
        DailyActivityDTO: {
            /** Count */
            count: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Level */
            level: number;
        };
        /** DailyGoalDTO */
        DailyGoalDTO: {
            /** Completed */
            completed: number;
            /** Target */
            target: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** NextMilestoneDTO */
        NextMilestoneDTO: {
            /** Days Remaining */
            days_remaining: number;
            /** Progress Pct */
            progress_pct: number;
            /** Target Days */
            target_days: number;
        };
        /** PackAdminDTO */
        PackAdminDTO: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Sort Order */
            sort_order: number;
            status: components["schemas"]["PackStatus"];
            /** Title */
            title: string;
        };
        /** PackCharacterDTO */
        PackCharacterDTO: {
            /** Hanzi */
            hanzi: string;
            /** Meaning */
            meaning: string;
            /** Pinyin */
            pinyin: string;
        };
        /** PackDetailDTO */
        PackDetailDTO: {
            /** Char Count */
            char_count: number;
            /** Characters */
            characters: components["schemas"]["PackCharacterDTO"][];
            /** Color */
            color: string;
            /** Glyph */
            glyph: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            progress: components["schemas"]["PackProgressDTO"];
            /** Sentence Count */
            sentence_count: number;
            /** Sentences */
            sentences: components["schemas"]["PackSentenceDTO"][];
            /** Slug */
            slug: string;
            /** Title */
            title: string;
        };
        /** PackProgressDTO */
        PackProgressDTO: {
            match: components["schemas"]["ActivityProgressDTO"];
            sentence: components["schemas"]["ActivityProgressDTO"];
            trace: components["schemas"]["ActivityProgressDTO"];
        };
        /** PackProgressResponseDTO */
        PackProgressResponseDTO: {
            /** Pack Slug */
            pack_slug: string;
            progress: components["schemas"]["PackProgressDTO"];
        };
        /** PackSentenceDTO */
        PackSentenceDTO: {
            /** Hanzi */
            hanzi: string;
            /** Pinyin */
            pinyin: string;
            /** Translation */
            translation: string;
        };
        /** PackSortOrderPatchDTO */
        PackSortOrderPatchDTO: {
            /** Sort Order */
            sort_order: number;
        };
        /**
         * PackStatus
         * @description Lifecycle status for a pack.
         * @enum {string}
         */
        PackStatus: "draft" | "published" | "retired";
        /** PackSummaryDTO */
        PackSummaryDTO: {
            /** Char Count */
            char_count: number;
            /** Color */
            color: string;
            /** Glyph */
            glyph: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            progress: components["schemas"]["PackProgressDTO"];
            /** Sentence Count */
            sentence_count: number;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
        };
        /** ProgressResetDTO */
        ProgressResetDTO: {
            /** Deleted Count */
            deleted_count: number;
            /** Pack Slug */
            pack_slug: string;
            progress: components["schemas"]["PackProgressDTO"];
        };
        /** ProgressSummaryDTO */
        ProgressSummaryDTO: {
            /** Activity */
            activity: components["schemas"]["DailyActivityDTO"][];
            /** Best Streak */
            best_streak: number;
            /** Current Streak */
            current_streak: number;
            daily_goal: components["schemas"]["DailyGoalDTO"];
            next_milestone: components["schemas"]["NextMilestoneDTO"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    patch_pack_api_v1_admin_packs__slug__patch: {
        parameters: {
            query?: never;
            header?: {
                ADMIN_TOKEN?: string | null;
            };
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PackSortOrderPatchDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackAdminDTO"];
                };
            };
            /** @description Missing or invalid admin token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Pack not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Admin endpoints disabled */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    publish_pack_api_v1_admin_packs__slug__publish_post: {
        parameters: {
            query?: never;
            header?: {
                ADMIN_TOKEN?: string | null;
            };
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackAdminDTO"];
                };
            };
            /** @description Missing or invalid admin token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Pack not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Admin endpoints disabled */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    retire_pack_api_v1_admin_packs__slug__retire_post: {
        parameters: {
            query?: never;
            header?: {
                ADMIN_TOKEN?: string | null;
            };
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackAdminDTO"];
                };
            };
            /** @description Missing or invalid admin token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Pack not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Admin endpoints disabled */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_character_strokes_api_v1_characters__hanzi__strokes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hanzi: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Hanzi Writer stroke JSON */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Character stroke data not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Path parameter must be exactly one grapheme */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_packs_api_v1_packs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackSummaryDTO"][];
                };
            };
        };
    };
    get_pack_api_v1_packs__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackDetailDTO"];
                };
            };
            /** @description Pack not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_completion_api_v1_progress_completions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompletionCreateDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletionResponseDTO"];
                };
            };
            /** @description Pack not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pack_progress_api_v1_progress_packs__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackProgressResponseDTO"];
                };
            };
            /** @description Pack not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_pack_progress_api_v1_progress_packs__slug__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressResetDTO"];
                };
            };
            /** @description Pack not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_progress_summary_api_v1_progress_summary_get: {
        parameters: {
            query?: {
                tz_offset_minutes?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressSummaryDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
