"""Generate TypeScript DTO types from the checked-in OpenAPI artifact."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

DEFAULT_INPUT = Path("docs/api/openapi-v1.json")
DEFAULT_OUTPUT = Path("src/habagou/web/frontend/src/lib/api-types.ts")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    document = json.loads(args.input.read_text(encoding="utf-8"))
    generated = generate_types(document)
    if args.check:
        if not args.output.exists():
            print(
                f"{args.output} does not exist; run generation first", file=sys.stderr
            )
            raise SystemExit(1)
        existing = args.output.read_text(encoding="utf-8")
        if existing != generated:
            print(
                f"{args.output} is stale; run `just openapi-export`",
                file=sys.stderr,
            )
            raise SystemExit(1)
        return

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generated, encoding="utf-8")


def generate_types(document: dict[str, Any]) -> str:
    schemas = document["components"]["schemas"]
    lines = [
        "/* This file is generated by scripts/generate_openapi_types.py. */",
        "/* Do not edit it by hand. */",
        "",
        "export type Components = {",
        "  schemas: {",
    ]
    for name in sorted(schemas):
        lines.append(f"    {json.dumps(name)}: {_schema_type(schemas[name])};")
    lines.extend(
        [
            "  };",
            "};",
            "",
        ]
    )
    return "\n".join(lines)


def _schema_type(schema: dict[str, Any]) -> str:
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])

    if "$ref" in schema:
        return _ref_type(schema["$ref"])

    if "anyOf" in schema:
        return " | ".join(_schema_type(item) for item in schema["anyOf"])

    schema_type = schema.get("type")
    if schema_type == "object":
        return _object_type(schema)
    if schema_type == "array":
        return f"{_array_item_type(schema['items'])}[]"
    if schema_type == "string":
        return "string"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"

    if schema.get("additionalProperties") is True:
        return "Record<string, unknown>"

    return "unknown"


def _object_type(schema: dict[str, Any]) -> str:
    properties = schema.get("properties", {})
    if not properties:
        if schema.get("additionalProperties") is True:
            return "Record<string, unknown>"
        return "Record<string, never>"

    required = set(schema.get("required", []))
    fields = []
    for name in sorted(properties):
        optional = "" if name in required else "?"
        fields.append(f"{json.dumps(name)}{optional}: {_schema_type(properties[name])}")
    return "{ " + "; ".join(fields) + " }"


def _ref_type(ref: str) -> str:
    prefix = "#/components/schemas/"
    if not ref.startswith(prefix):
        raise ValueError(f"unsupported OpenAPI ref: {ref}")
    name = ref.removeprefix(prefix)
    return f'Components["schemas"][{json.dumps(name)}]'


def _array_item_type(schema: dict[str, Any]) -> str:
    item_type = _schema_type(schema)
    if " | " in item_type:
        return f"({item_type})"
    return item_type


if __name__ == "__main__":
    main()
